
server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/gamification
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update